### ISSUE TITLE
Documentation confusion - DB, DB_EXISTS, MD5,Authenticate, AGI  etc are core asterisk not FreePBX

### ISSUE THREAD

**Issue by lardconcepts** [ossobv/asterisklint#12]
In the README, it says:

> Add functions DB, DB_EXISTS, MD5 (as used in FreePBX dialplan).
> Add apps Authenticate, AGI (as used in FreePBX dialplan).

However, these are pretty core Asterisk functions and apps.

**Comment by wdoekes** [comment]
I did not mean that they weren't.

I don't use them myself, but I ran in to them when running asterisklint against a stock FreePBX dialplan.
