### ISSUE TITLE
E_APP_ARG_MANY gosub freeze endless check with 100% cpu core load

### ISSUE THREAD

**Issue by utrumo** [ossobv/asterisklint#41]
I have make syntax mistake - added excess comma before opening bracket in gosub:
`exten => _7495XXXXXXX,1,Gosub(sub-dial,${EXTEN},1,(${SOME_VARIABLE}))`

When i start `asterisklint dialplan-check extensions.conf` it freeze with 100% one core cpu load and this message in console:
`extensions.conf:44 E_APP_ARG_MANY: too many arguments for app 'Gosub', maximum is 3`

P.S. I broke by this error your site: https://asterisklint.osso.pub/
I'm sorry! :))

**Comment by wdoekes** [comment]
Thanks for the report!

Bug has been fixed. Website has been fixed. New release has been made.
