### ISSUE TITLE
missing asterisk built in functions

### ISSUE THREAD

**Issue by perkons** [ossobv/asterisklint#49]
OpenBSD 6.8
Asterisk 18.1.1

```
E_FUNC_MISSING: function does not exist (or func_odbc created?):
'DEVICE_STATE'
'DIALGROUP'
'DIALPLAN_EXISTS'
'PJSIP_DIAL_CONTACTS'
```

Links to the function docs:
https://wiki.asterisk.org/wiki/display/AST/Function_DEVICE_STATE
https://wiki.asterisk.org/wiki/display/AST/Function_DIALGROUP
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Function_DIALPLAN_EXISTS
https://wiki.asterisk.org/wiki/display/AST/Asterisk+15+Function_PJSIP_DIAL_CONTACTS

**Comment by wdoekes** [comment]
Yes. I haven't been updating the list of available functions for a while. This was bound to happen.

Thanks for the report!

**Comment by jjsearle** [comment]
I have included these (+ others) in the following pull request
https://github.com/ossobv/asterisklint/pull/50

**Comment by wdoekes** [comment]
Thanks! Should be fixed.
